# Generated by Django 3.1.4 on 2020-12-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikemuch_app', '0002_auto_20201207_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(default=0, max_length=2)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikemuch_app.hike')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikemuch_app.hike')),
            ],
        ),
    ]
