# Generated by Django 3.1.4 on 2020-12-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikemuch_app', '0003_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='pet',
            new_name='hike',
        ),
    ]
